[package]
name = "substrate-chain-spec"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
substrate-chain-spec-derive = { path = "./derive" }
impl-trait-for-tuples = "0.1.3"
network = { package = "substrate-network", path = "../../client/network" }
primitives = { package = "substrate-primitives", path = "../primitives" }
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
sr-primitives = { path = "../../client/sr-primitives" }
tel = { package = "substrate-telemetry", path = "../../client/telemetry" }

[dev-dependencies]
