[workspace]
members = [
	"client/authority-discovery",
	"client/application-crypto",
	"client/chain-spec",
	"client/chain-spec/derive",
	"client/cli",
	"client/client",
	"client/client/db",
	"client/client/header-metadata",
	"client/consensus/aura",
	"client/consensus/babe",
	"client/consensus/common",
	"client/consensus/rhd",
	"client/consensus/slots",
	"client/consensus/uncles",
	"client/consensus/pow",
	"client/executor",
	"client/executor/runtime-test",
	"client/externalities",
	"client/finality-grandpa",
	"client/finality-grandpa/primitives",
	"client/inherents",
	"client/keyring",
	"client/keystore",
	"client/network",
	"client/panic-handler",
	"client/primitives",
	"client/rpc",
	"client/rpc/primitives",
	"client/rpc-servers",
	"client/serializer",
	"client/service",
	"client/service/test",
	"client/session",
	"client/sr-api-macros",
	"client/sr-arithmetic",
	"client/sr-io",
	"client/sr-primitives",
	"client/sr-staking-primitives",
	"client/sr-sandbox",
	"client/sr-std",
	"client/sr-version",
	"client/state-machine",
	"client/telemetry",
	"client/test-client",
	"client/test-runtime",
	"client/test-runtime/client",
	"client/transaction-pool",
	"client/transaction-pool/graph",
	"client/trie",
	"client/utils/fork-tree",
	"client/utils/wasm-builder",
	"client/utils/wasm-builder-runner",
	"client/wasm-interface",
	"srml/support",
	"srml/support/procedural",
	"srml/support/procedural/tools",
	"srml/support/procedural/tools/derive",
	"srml/support/test",
	"srml/authorship",
	"srml/assets",
	"srml/aura",
	"srml/balances",
	"srml/contracts",
	"srml/contracts/rpc",
	"srml/collective",
	"srml/democracy",
	"srml/elections",
	"srml/elections-phragmen",
	"srml/example",
	"srml/executive",
	"srml/finality-tracker",
	"srml/generic-asset",
	"srml/grandpa",
	"srml/im-online",
	"srml/authority-discovery",
	"srml/indices",
	"srml/membership",
	"srml/metadata",
	"srml/nicks",
	"srml/offences",
	"srml/randomness-collective-flip",
	"srml/scored-pool",
	"srml/session",
	"srml/staking",
	"srml/staking/reward-curve",
	"srml/sudo",
	"srml/system",
	"srml/system/rpc",
	"srml/timestamp",
	"srml/treasury",
	"srml/transaction-payment",
	"srml/transaction-payment/rpc",
	"srml/utility",
	"srml/evm",
	"bin/node/cli",
	"bin/node/executor",
	"bin/node/primitives",
	"bin/node/rpc",
	"bin/node/rpc-client",
	"bin/node/runtime",
	"bin/node/testing",
	"bin/node-template",
	"bin/subkey",
	"test/utils/chain-spec-builder",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"

