[package]
name = "substrate-service"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[features]
default = ["rocksdb"]
# The RocksDB feature activates the RocksDB database backend. If it is not activated, and you pass
# a path to a database, an error will be produced at runtime.
rocksdb = ["client_db/kvdb-rocksdb"]
wasmtime = [
    "substrate-executor/wasmtime",
]

[dependencies]
derive_more = "0.15.0"
futures = "0.1.29"
futures03 = { package = "futures-preview", version = "0.3.0-alpha.19", features = ["compat"] }
parking_lot = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.8"
slog = { version = "2.5.2", features = ["nested-values"] }
tokio-executor = "0.1.8"
tokio-timer = "0.2.11"
exit-future = "0.1.4"
serde = "1.0.101"
serde_json = "1.0.41"
sysinfo = "0.9.5"
target_info = "0.1.0"
keystore = { package = "substrate-keystore", path = "../../client/keystore" }
sr-io = { path = "../../client/sr-io" }
sr-primitives = { path = "../../client/sr-primitives" }
primitives = { package = "substrate-primitives", path = "../primitives" }
session = { package = "substrate-session", path = "../session" }
app-crypto = { package = "substrate-application-crypto", path = "../application-crypto" }
consensus_common = { package = "substrate-consensus-common", path = "../../client/consensus/common" }
network = { package = "substrate-network", path = "../../client/network" }
chain-spec = { package = "substrate-chain-spec", path = "../chain-spec" }
client = { package = "substrate-client", path = "../../client/client" }
client_db = { package = "substrate-client-db", path = "../../client/client/db" }
codec = { package = "parity-scale-codec", version = "1.0.0" }
substrate-executor = { path = "../../client/executor" }
transaction_pool = { package = "substrate-transaction-pool", path = "../../client/transaction-pool" }
rpc-servers = { package = "substrate-rpc-servers", path = "../../client/rpc-servers" }
rpc = { package = "substrate-rpc", path = "../../client/rpc" }
tel = { package = "substrate-telemetry", path = "../../client/telemetry" }
offchain = { package = "substrate-offchain", path = "../../client/offchain" }
parity-multiaddr = { package = "parity-multiaddr", version = "0.5.0" }

[dev-dependencies]
substrate-test-runtime-client = { path = "../../test/utils/runtime/client" }
node-executor = { path = "../../bin/node/executor" }
node-primitives = { path = "../../bin/node/primitives" }
node-runtime = { path = "../../bin/node/runtime" }
babe-primitives = { package = "substrate-consensus-babe-primitives", path = "../../client/consensus/babe/primitives" }
grandpa = { package = "substrate-finality-grandpa", path = "../../client/finality-grandpa" }
grandpa-primitives = { package = "substrate-finality-grandpa-primitives", path = "../../client/finality-grandpa/primitives" }
tokio = "0.1"
