[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", path = "../../../client/client" }
jsonrpc-core = "14.0.3"
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }
sr-primitives = { path = "../../../client/sr-primitives" }
srml-contracts-rpc = { path = "../../../srml/contracts/rpc/" }
srml-transaction-payment-rpc = { path = "../../../srml/transaction-payment/rpc/" }
srml-system-rpc = { path = "../../../srml/system/rpc/" }
transaction_pool = { package = "substrate-transaction-pool", path = "../../../client/transaction-pool" }
